<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMaDF2h1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMaDF2h1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMaDF2h1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMaDF2h1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMaDF2h1\App_KernelDevDebugContainer([
    'container.build_hash' => 'MaDF2h1',
    'container.build_id' => '32588f0d',
    'container.build_time' => 1712921342,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMaDF2h1');
